version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_FZ9YN7oCPJnu
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: